require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-packaging
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - gemfiles/*
    - spec/dummy/**/*

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: False

RSpec/MultipleExpectations:
  Enabled: false